print("Calcul de l'Extractif Non Azoté ou ENA, qui permet d'avoir une approximation des glucides.\n\nAttention, il s'agit d'une estimation, et pas d'un dosage.\n\nCela signifie que vous ne pouvez pas établir de classement ou de score Petfood avec ce résultat ENA, à cause de cette imprécision.")
print("\n\n")
a = int(input("Indiquez le pourcentage des protéines brutes "))
b = int(input("Indiquez le pourcentage des matières grasses "))
c = int(input("Indiquez le pourcentage des cendres brutes "))
d = int(input("Indiquez le pourcentage des fibres brutes "))
d = int(input("Indiquez le pourcentage d'humidité (indiquez 10 en l'absence de mention) "))
ena = 100-(a+b+c+d)
print(f"Le résultat de la formule ENA (simple estimation des glucides avec une grande marge d'erreur) est : {ena}")